### ISSUE TITLE
attempt to call method 'SetBackdrop' (a nil value)

### ISSUE THREAD

**Issue by mainframecn** [mbecker6/SellCrap#1]
Date: 2021-08-26 19:23:04
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\SellCrap\bagCrapValue.lua line 42:
   attempt to call method 'SetBackdrop' (a nil value)
Debug:
   [string "=[C]"]: SetBackdrop()
   [string "@SellCrap\bagCrapValue.lua"]:42: in main chunk
Locals:

AddOns:
  Swatter, v1.13.6652 (SwimmingSeadragon)
  Atlas, vv1.49.01
  AtlasBurningCrusade, vv1.49.00
  AtlasClassicWoW, vv1.49.00
  AtlasTransportation, vv1.49.00
  AtlasLootClassic, vv2.3.2-bcc
  AtlasLootClassicData, vv2.3.2-bcc
  AtlasLootClassicDungeonsAndRaids, vv2.3.2-bcc
  AucAdvanced, v1.13.6717 (SwimmingSeadragon)
  AucFilterBasic, v1.13.6680 (SwimmingSeadragon)
  AucStatHistogram, v1.13.6681 (SwimmingSeadragon)
  AucStatiLevel, v1.13.6705 (SwimmingSeadragon)
  AucStatPurchased, v1.13.6672 (SwimmingSeadragon)
  AucStatSimple, v1.13.6634 (SwimmingSeadragon)
  AucStatStdDev, v1.13.6635 (SwimmingSeadragon)
  AucUtilFixAH, v1.13.6608 (SwimmingSeadragon)
  AuctionDB, vv1.05.02
  BadBoy, vv2-classic
  BagBrother, v
  Bagnon, v9.1.0
  Bartender4, v4.10.10
  BeanCounter, v1.13.6682 (SwimmingSeadragon)
  BetterVendorPrice, vv1.15.00
  ClassicCodex, vv0.4.9
  ClassicCodexdb, vv0.4.9
  ClassicCodexdbenUS, vv0.4.9
  ClassicCodexloader, vv0.4.9
  ClassicCodexpatch, vv0.4.9
  DBMCore, v2.5.10
  DBMSoundEventsPack, v1.6.11
  DBMStatusBarTimers, v
  Decursive, v2.7.8.3
  Enchantrix, v1.13.6708 (SwimmingSeadragon)
  EnchantrixBarker, v1.13.6697 (SwimmingSeadragon)
  FishingBuddy, v0.7.5.5
  GatherMate2, v1.46.1-classic
  HealBot, v2.5.1.16
  HealBotData, v2.5.1.16
  HealBoten, v2.5.1.16
  HealBotOptions, v2.5.1.16
  Immersion, v1.3.7
  NovaWorldBuffs, v2.14
  Pawn, v2.5.25
  Plater, vPlater-v337-BCC
  Questie, v6.5.1
  RareScanner, v2.5.1
  SellCrap, v1.4
  SexyMap, vv5-bcc
  SlideBar, v1.13.6668 (SwimmingSeadragon)
  Stubby, v1.13.6614 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v2.5.1.20501 <none>
  (ck=64a)

**Comment by mbecker6** [comment]
Thanks for pointing that out. I will take a look at it.
